---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tangogql.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tangogql.name" . }}-{{ .Release.Name }}
    chart: {{ template "tangogql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: tangogql-tcp
    port: 5004
    targetPort: tangogql-tcp
    protocol: TCP
  selector:
    app: {{ template "tangogql.name" . }}-{{ .Release.Name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tangogql.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tangogql.name" . }}-{{ .Release.Name }}
    chart: {{ template "tangogql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "tangogql.name" . }}-{{ .Release.Name }}
  serviceName: {{ template "tangogql.name" . }}-{{ .Release.Name }}
  replicas: {{ .Values.tangogql.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "tangogql.name" . }}-{{ .Release.Name }}
        chart: {{ template "tangogql.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      initContainers:
      - name: waitdatabaseds
        image: "{{ .Values.itango.image.registry }}/{{ .Values.itango.image.image }}:{{ .Values.itango.image.tag }}"
        imagePullPolicy: IfNotPresent
        command:
          - /usr/local/bin/wait-for-it.sh
          - {{ default .Values.global.tango_host .Values.tango_host }}
          - --timeout=30
          - --strict
          - --
          - echo "Databaseds ready for use."
      containers:
      - name: tangogql
        image: "{{ .Values.tangogql.image.registry }}/{{ .Values.tangogql.image.image }}:{{ .Values.tangogql.image.tag }}"
        imagePullPolicy: {{ .Values.tangogql.image.pullPolicy }}
        volumeMounts:
        - mountPath: /var/log/tangogql
          name: tangogql-logs
        env:
          - name: LOG_PATH
            value: "/var/log/tangogql"
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: TANGO_HOST
            value: {{ default .Values.global.tango_host .Values.tango_host }}
          - name: TANGOGQL_NO_AUTH
            value: {{ default .Values.global.no_auth | quote }}
          - name: TANGOGQL_ATTRIBUTE_CLIENT_QUEUE_LIMIT
            value: {{ .Values.global.attribute_client_queue_limit | quote }}
          - name: TANGOGQL_ATTRIBUTE_GLOBAL_QUEUE_LIMIT
            value: {{ .Values.global.attribute_global_queue_limit | quote }}
          - name: TANGOGQL_OIDC_ISSUER
            value: {{ .Values.global.oidc_issuer | quote }}
          - name: TANGOGQL_MSENTRA_TENANT_ID
            value: {{ .Values.global.msentra_tenant_id | quote }}
          - name: TANGOGQL_MSENTRA_API_ID
            value: {{ .Values.global.msentra_api_id | quote }}
          - name: TANGOGQL_MSENTRA_READ_ACCESS
            value: {{ .Values.global.msentra_read_access | quote }}
          - name: TANGOGQL_MSENTRA_READWRITE_ACCESS
            value: {{ .Values.global.msentra_readwrite_access | quote }}
          - name: TANGOGQL_IAMS_AUTHORITY
            value: {{ .Values.global.iams_authority | quote }}
          - name: TANGOGQL_IAMS_CLIENT_ID
            value: {{ .Values.global.iams_client_id | quote }}
          - name: TANGOGQL_IAMS_API_AUDIENCE
            value: {{ .Values.global.iams_api_audience | quote }}
          - name: TANGOGQL_IAMS_REQUIRE_AUDIENCE
            value: {{ .Values.global.iams_require_audience | quote }}
          - name: TANGOGQL_IAMS_READ_GROUP
            value: {{ .Values.global.iams_read_group | quote }}
          - name: TANGOGQL_IAMS_READWRITE_GROUP
            value: {{ .Values.global.iams_readwrite_group | quote }}
        ports:
        - name: tangogql-tcp
          containerPort: 5004
          protocol: TCP
        resources:
{{ toYaml .Values.tangogql.resources | indent 10 }}

      volumes:
      - name: logging-config
        configMap:
          name: config-{{ template "tangogql.name" . }}-{{ .Release.Name }}
      - name: tangogql-logs
        persistentVolumeClaim:
          claimName: {{ template "tangogql.name" . }}-{{ .Release.Name }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
